name: QA

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        dependencies: ['--prefer-lowest', '']

    name: PHP ${{ matrix.php }} ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer update --no-progress ${{ matrix.dependecies }}

      - name: PHPStan
        run: vendor/bin/phpstan analyse

      - name: Tester
        run: vendor/bin/tester -C tests/unit
